version: "3.9"
services:
  gateway:
    build: server/gateway
    ports:
      - "3000:3000"
  app-service:
    build: server/app
    ports:
      - "4001:4001"
  user-service:
    build: server/user
    ports:
      - "4002:4002"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"